Repository wecode-bootcamp-korea/46-1st-BestFriend-frontend, pull requests merged in 2023-06, with the labels that each got.

#4 [46기 조혜진] Add : Nav UI 추가
  public/images/Nav/cart.png
  public/images/Nav/like.png
  public/images/Nav/user.png
  src/Router.js
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.scss
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Subcategory/Subcategory.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/styles/mixin.scss
Labels: 멘토 리뷰 요청, 수정 완료

#2 [46기 조혜진] Add : ProductList(Plants) UI 추가
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청, 수정 완료

#3 [46기 이재웅] Add : Cart UI 추가
  public/images/ProductDetail/plant-21.jpg
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/component/CartBox.js
  src/pages/Cart/component/CartBox.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청, 수정 완료

#1 [46기 이재웅] Add : ProductDetail UI 추가
  public/data/productDetail.json
  public/data/recommend.json
  public/images/ProductDetail/plant-10.jpg
  src/Router.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/component/Recommend.js
  src/pages/ProductDetail/component/Recommend.scss
Labels: 수정 완료

#7 [46기 장건웅]Add : Login UI 추가 및 인증 기능 구현
  public/data/login.json
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 완료

#9 [46기 장건웅]Add : Checkout UI 추가
  public/data/productList.json
  public/data/userInfo.json
  src/pages/Checkout/Checkout.js
  src/pages/Checkout/Checkout.scss
  src/pages/Checkout/CheckoutList.js
  src/pages/Checkout/CheckoutList.scss
Labels: 멘토 리뷰 요청, 수정 완료

#10 [46기 조혜진] Add : Main UI 추가
  src/components/MainMessage/MainMessage.js
  src/components/MainMessage/MainMessage.scss
  src/components/MainPlantCard/MainPlantCard.js
  src/components/MainPlantCard/MainPlantCard.scss
  src/components/MainPotCard/MainPotCard.js
  src/components/MainPotCard/MainPotCard.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청, 수정 완료

#13 Style : 공통 스타일 수정
  src/components/Footer/Footer.js
  src/components/MainMessage/MainMessage.js
  src/components/Nav/Nav.js
  src/pages/Cart/Cart.scss
  src/pages/Login/Login.scss
  src/pages/Signup/Signup.scss
  src/styles/common.scss
Labels: 도움 요청, 멘토 리뷰 요청

#14 [46기 조혜진] 메인 페이지 콘텐츠&링크 수정
  .stylelintrc.js
  src/components/MainContent/MainContent.js
  src/components/MainMessage/MainMessage.js
  src/components/MainPlantCard/MainPlantCard.js
  src/components/MainPlantCard/MainPlantCard.scss
  src/components/MainPotCard/MainPotCard.js
  src/components/MainPotCard/MainPotCard.scss
  src/components/Nav/Nav.scss
  src/images/gron-symbol-white.png
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청, 수정 완료

#18 [46기 장건웅]Feature: login,signup에서 Nav,Footer 분리
  src/Container.js
  src/Router.js
Labels: 멘토 리뷰 요청

#11 [46기 이재웅] Feature : Cart-AddToCart
  public/data/cartData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/component/CartBox.js
  src/pages/Cart/component/CartBox.scss
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청, 수정 완료

#17 [46기 장건웅]Feature: 회원가입 기능 추가
  public/data/userSignup.json
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 완료

#19 [46기 장건웅]Feature: 로그인 성공시 Navbar 내 로그인버튼->유저아이콘 변경
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 수정 완료

#12 [46기 이재웅] Feature : ProductDetail-Count
  package-lock.json
  package.json
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Nav/Nav.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/component/Recommend.js
  src/pages/ProductDetail/component/Recommend.scss
Labels: 완료

#20 [46기 조혜진] Feature : 상품 리스트 서브카테고리 선택, 필터링, 정렬, 페이지네이션, 검색
  public/data/productList.json
  public/images/ProductList/sort.png
  src/components/Category/Category.js
  src/components/Category/Category.scss
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.scss
  src/components/Filter/Filter.js
  src/components/Filter/Filter.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.scss
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/components/Search/Search.js
  src/components/Search/Search.scss
  src/components/Sort/Sort.js
  src/components/Sort/Sort.scss
  src/components/Subcategory/Subcategory.js
  src/constants.js
  src/pages/Main/Main.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: 멘토 리뷰 요청

#23 [46기 조혜진] Add : 리뷰 컴포넌트 UI 추가 & 리뷰 남기기 기능 구현
  public/images/ProductDetail/trash.png
  src/components/Review/Review.js
  src/components/Review/Review.scss
  src/pages/ProductDetail/ProductDetail.js
Labels: 완료

#27 [46기 이재웅] Feature : 상품 클릭시 디테일페이지 이동
  src/pages/Cart/Cart.js
  src/pages/Cart/component/CartBox.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/Wishlist/Wishlist.js
  src/pages/Wishlist/component/WishlistBox.js
Labels: 완료

#25 [46기 이재웅] Add : 캐러셀 UI 구현
  src/Router.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청, 수정 완료

#28 [46기 장건웅]Feature: 로그인 실패시 login toast팝업 추가
  src/components/Toast/Toast.js
  src/components/Toast/Toast.scss
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청, 수정 완료

#32 [46기 장건웅]Modify: checkout style
  src/pages/Checkout/Checkout.scss
  src/pages/Checkout/CheckoutList.scss
Labels: 멘토 리뷰 요청

#30 [46기 조혜진] Fix : Merge 후 발생한 오류 해결
  src/components/MainContent/MainContent.js
  src/components/MainPlantCard/MainPlantCard.js
  src/components/Nav/Nav.js
  src/components/ProductCard/ProductCard.js
  src/components/Sort/Sort.js
  src/pages/Cart/Cart.js
  src/pages/Cart/component/CartBox.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/ProductList.js
  src/pages/Signup/Signup.js
  src/pages/Wishlist/Wishlist.js
  src/pages/Wishlist/component/WishlistBox.js
Labels: 리뷰 진행 중, 수정 완료

#33 [46기 장건웅]Refactor: input 메시지 리팩토링, 분기처리추가,스타일 수정
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청, 수정 완료

#35 [46기 이재웅] Merge Error 및 스타일 수정
  src/components/Dropdown/Dropdown.scss
  src/components/MainContent/MainContent.js
  src/components/MainPlantCard/MainPlantCard.js
  src/components/MainPlantCard/MainPlantCard.scss
  src/components/MainPotCard/MainPotCard.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/components/Review/Review.js
  src/components/Search/Search.js
  src/components/Toast/Toast.scss
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/component/CartBox.js
  src/pages/Cart/component/CartBox.scss
  src/pages/Checkout/Checkout.js
  src/pages/Checkout/Checkout.scss
  src/pages/Checkout/CheckoutList.js
  src/pages/Checkout/CheckoutList.scss
  src/pages/Checkout/CheckoutModal.js
  src/pages/Checkout/CheckoutModal.scss
  src/pages/Checkout/CheckoutToast.js
  src/pages/Checkout/CheckoutToast.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/ProductList.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Wishlist/Wishlist.js
  src/pages/Wishlist/component/WishlistBox.scss
Labels: 멘토 리뷰 요청

#36 [46기 장건웅] Modify: style 긴급수정
  src/components/Toast/Toast.scss
Labels: 멘토 리뷰 요청
